# Generated by Django 6.1 on 2026-09-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0002_couple'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupleinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
    ]
