# Generated by Django 6.1 on 2026-09-21 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0003_coupleinvite_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couples_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='couple',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couples_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='couple',
            constraint=models.UniqueConstraint(fields=('user1',), name='unique_user1_couple'),
        ),
        migrations.AddConstraint(
            model_name='couple',
            constraint=models.UniqueConstraint(fields=('user2',), name='unique_user2_couple'),
        ),
        migrations.AddConstraint(
            model_name='couple',
            constraint=models.CheckConstraint(condition=models.Q(('user1', models.F('user2')), _negated=True), name='couple_users_must_be_different'),
        ),
    ]
