# Generated by Django 6.1 on 2026-09-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0004_alter_couple_user1_alter_couple_user2_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='couple',
            name='unique_user1_couple',
        ),
        migrations.RemoveConstraint(
            model_name='couple',
            name='unique_user2_couple',
        ),
        migrations.RemoveConstraint(
            model_name='couple',
            name='couple_users_must_be_different',
        ),
    ]
