# Generated by Django 6.1 on 2026-09-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Man', 'Мужской'), ('Woman', 'Женский')], max_length=20, verbose_name='Пол'),
        ),
    ]
